const Strings = {
    signup: 'Sign Up',
    login: 'Login',
    firstName: "First Name",
    lastName: 'Last Name',
    emailAddress: "Email Address",
    phoneNumber: 'Phone Number',
    password: 'Password',
    firstNameRequired: 'First name is required!',
    firstNameMatch: 'First name should contain only letters',
    firstNameMinLength: 'First name must contain atleast 2 letters',
    firstNameMaxLength: 'First name should contain atmost 20 letters',
    lastNameRequired: 'Last name is required!',
    lastNameMatch: 'Last name should contain only letters',
    lastNameMinLength: 'Last name must contain atleast 2 letters',
    lastNameMaxLength: 'Last name should contain atmost 20 letters',
    invalidEmail: 'Invalid email!',
    emailMustBeValidFormat: "Email must be a valid format",
    emailRequired: 'Email is required!',
    phoneRequired: 'Phone number is required!',
    phoneNumberMatch: "Phone number must be exactly 10 digits and start with 6-9",
    passwordRequired: 'Password is required!',
    passwordMinLength: 'Password must be atleast 8 characters long!',
    passwordCapitalLetterMatch: 'Password must contain atleast 1 capital letter(A-Z)',
    passwordSmallLetterMatch: 'Password must contain atleast 1 small letter(a-z)',
    passwordNumberMatch: 'Password must contain atleast 1 number(0-9)',
    passwordSpecialCharactersMatch: 'Password must contain atleast 1 special character(!@#$%^&*)',
    continuewithGoogle: "Continue with Google",
    continuewithapple: "Continue with Apple",
    continuewithMicrosoft: "Continue with Microsoft",
    alreadyHaveAccount: 'Already have cccount?',
    newUser: 'New user?',
    register: 'Register',
    or:'or',
    error: 'Error',
    success: 'Success',
    info: 'Info',
    phoneNumberError: 'UNIQUE constraint failed: user_table.phone (code 2067 SQLITE_CONSTRAINT_UNIQUE)',
    emailError: 'UNIQUE constraint failed: user_table.email (code 2067 SQLITE_CONSTRAINT_UNIQUE)',
    duplicateError: 'Duplicate error',
    loginError: 'Login error',
    soemthingWentWrong: 'Something went wrong!!',
    thisPhoneNumberIsAlreadyRegsitered: 'This number is already registered. Please try different phone number!',
    thisemailIsAlreadyRegsitered: 'This email is already registered. Please try different email !',
    loginCredentialsError: 'Login credentials is not correct !',
    userDoesNotExist: 'User does not exist!',
    signInCancelled: 'User has cancelled the sign in request'
}

export default Strings